#
# application.yml — главный конфигурационный файл Spring Boot.

Что нужно сделать:
  - Указать настройки подключения к базе данных.
  - Указать порт приложения.
  - Настроить параметры безопасности и JWT.
  - Включить Swagger UI.
  -
server:
  port: 8080

spring:
  application:
    name: bankcard

  profiles:
    active: default #сменить при завершении

  security:
    secretKeyCard: 'some-very-long-random-secret-key-12341-12321-6589-87889'
    jwt:
      token:
        secret: 'some-very-long-random-secret-key-at-least-32-bytes'
        access-expiration: 900000

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:/db/migration/changelog-master.yaml
