#
# application.yml — главный конфигурационный файл Spring Boot.

Что нужно сделать:
  - Указать настройки подключения к базе данных.
  - Указать порт приложения.
  - Настроить параметры безопасности и JWT.
  - Включить Swagger UI.
  -
server:
  port: 8080

spring:
  application:
    name: bankcard

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect


  liquibase:
    enabled: true
    change-log: classpath:/db/migration/changelog-master.yaml


  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    liquibase: INFO